### ISSUE TITLE
not actually inverting eddb.io

### ISSUE THREAD

**Issue by Soyaro666** [CynderR/i-Eye#2]
Well, here's the default look of eddb.io on the left, the "inverted" version on the right. Not quite what I'd expect...
![image](https://user-images.githubusercontent.com/12465756/57197269-89746f00-6f65-11e9-8174-8a32ae800d30.png)

**Comment by CynderR** [comment]
Thanks for the input and the screenshot!
I added a bit of code that will fix this, although this code is still not perfect. Its not going to invert everything (and the cookie warning on eddb.io also did not look great...
